apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  selector:
    component: helm
    app: nginx
  ports:
    - protocol: TCP
      port: 80   #service port
      targetPort: {{ .Values.configmap.port }}  #pod port