apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
  namespace: expense
spec:
  selector:
    app: expense
    tier: db
    component: mysql
  ports:
    - protocol: TCP
      port: 3306   #service port
      targetPort: 3306  #pod port