kind: ConfigMap
apiVersion: v1
metadata:
 name: backend-configmap
 namespace: expense
data: 
  DB_HOST: mysql-service #mysql component service name
#configmap details to tell backend to connect to mysql service